#!/usr/bin/env bash
#Just a comment

while IFS=":" read -r username paswd uid gid info homedir choms
do
	echo "The user $username is part of the $gid gang, lives in $homedir and rides $choms. $uid's place is protected by the passcode $paswd, more info about the user here: $info"
done < /etc/passwd
