#!/usr/bin/env bash
#File test
if [ -e "./school" ]
then
	echo "school file exists"

	#If empty
	if [ -s "./school" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	#If regular
	if [ -f "./school" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
